### PR TITLE
update to scala 2.13.0

### PR DESCRIPTION
**Pull request by OlegYch**
had to convert errorreportingparser to java because of a bug in 2.13.0 https://github.com/scala/bug/issues/11584

### CODE REVIEW

**Comment by makkarpov** [comment]
Thank you for your work!

**Comment by OlegYch** [comment]
@makkarpov please release

**Comment by OlegYch** [comment]
@makkarpov ping

**Comment by makkarpov** [comment]
Sorry for the delay, unfortunately publishing of this version is not so trivial - SBT breaks in various funny ways, either producing duplicate artifacts, complaining about broken or incompatible classes and something like this. I will notify when I will resolve these issues.

**Comment by makkarpov** [comment]
Well, our world is full of magic. Tried same actions in separate clean Docker image and this helped. It seems that I have corrupted SBT state or something like this.

I had released this version as 0.8.1.

**Comment by OlegYch** [comment]
@makkarpov cheers

**Pull request merged**
