### PR TITLE
ensure the produced files are system-independent, fix locations ordering and tests

### PR DESCRIPTION
**Pull request by OlegYch**
This fixes line and path separators to UNIX standard to ensure the generated files are consistent across developers.
And also accidentally fixes locations ordering in generated files and running scripted tests on windows.
Apologies for mixed concerns.

### CODE REVIEW

**Comment by makkarpov** [comment]
Thank you for your pull request! I'll publish updated version to Maven soon.

**Comment by OlegYch** [comment]
thanks!

**Comment by OlegYch** [comment]
@makkarpov could you publish it please

**Comment by makkarpov** [comment]
Sorry, completely forgot about it. Five minutes.

**Comment by makkarpov** [comment]
https://oss.sonatype.org/content/repositories/releases/ru/makkarpov/scalingua_2.12/0.7.3/

But it sill isn't on Maven Central yet. Maven Central sync usually takes about ~30 minutes.

**Comment by OlegYch** [comment]
cheers, works as expected

**Pull request merged**
